Let's begin learning some NumPy today

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [24]:
import numpy as np
import time

In [5]:
a = np.zeros(4)

print(f"a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")

a = [0. 0. 0. 0.], a.shape = (4,), a data type = float64


In [6]:
a = np.arange(4.)

print(f"a = {a}, a.shape = {a.shape}, a datatype = {a.dtype}")

a = [0. 1. 2. 3.], a.shape = (4,), a datatype = float64


In [7]:
a = np.array([2,5,6,7,1])

print(f"a = {a}, a.shape = {a.shape}, a datatype = {a.dtype}")

a = [2 5 6 7 1], a.shape = (5,), a datatype = int64


Let's checkout Indexing now

In [8]:
a = np.arange(10)
print(a)

print(f"a[2] = {a[2]}, a[2].shape = {a[2].shape}")

print(f"a[-1] = {a[-1]}")

try:
    x = a[10]
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2] = 2, a[2].shape = ()
a[-1] = 9
index 10 is out of bounds for axis 0 with size 10


Let's cover some Slicing now

In [15]:
a = np.arange(10)

# start end step
b = a[0:9:2]
print(b)

b = a[2:]
print(b)

b = a[:5]
print(b)

b = a[-5:]
print(b)

[0 2 4 6 8]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]


Let's explore some Vector operations now

In [20]:
a = np.array([5,6,7,8,9])

b = -a
print(b)

b = np.sum(a)
print(b)

b = 5*a
print(b)

b = a**4
print(b)

[-5 -6 -7 -8 -9]
35
[25 30 35 40 45]
[ 625 1296 2401 4096 6561]


In [19]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a+b)

c = np.array([2,3])

try:
    d = a+c
except Exception as e:
    print(e)

[ 6  8 10 12]
operands could not be broadcast together with shapes (4,) (2,) 


Now let's work on the Dot Product

In [22]:
def manual(a,b):
    x = 0

    for i in range(a.shape[0]):
        x += a[i]*b[i]
    
    return x

In [23]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.dot(a,b))
print(manual(a,b))

70
70


Now let's perform a comparison

In [25]:
np.random.seed(1)

a = np.random.rand(100000)
b = np.random.rand(100000)

tick = time.time()
c = np.dot(a,b)
tock = time.time()

print(f"Vectorized version duration = {1000*(tock-tick)} milliseconds")

tick = time.time()
c = manual(a,b)
tock = time.time()

print(f"Manual loop version duration = {1000*(tock-tick)} milliseconds")

del(a)
del(b)

Vectorized version duration = 2.5184154510498047 milliseconds
Manual loop version duration = 41.3212776184082 milliseconds


We'll just briefly checkout some matrix setup and operations

In [28]:
a = np.zeros((3,5))
print(f"a = {a}, a.shape = {a.shape}")

a = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], a.shape = (3, 5)


In [33]:
a = np.arange(6).reshape(2,3)
print(f"a = {a}, a.shape = {a.shape}")

a = [[0 1 2]
 [3 4 5]], a.shape = (2, 3)
